# Copyright (C) 2021 Casper Meijn <casper@meijn.net>
#
# SPDX-License-Identifier: CC0-1.0

tasks:
  - init: |
      rustup component add clippy
      curl -sf https://gobinaries.com/aevea/commitsar@v0.17.0 | sh
      pip3 install --user reuse
      cargo build
      cargo test
    command: |
      cargo run
vscode:
  extensions:
    - vivaxy.vscode-conventional-commits
    - matklad.rust-analyzer
